---
- name: Configure DS URI in deploymentclient.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: 'target-broker:deploymentServer'
    option: targetUri
    value: "{{ splunk_uri_ds }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - splunk_uri_ds != 'undefined'
    - "'indexer' not in group_names"
    - "'search' not in group_names"
    - "'splunk_mgmt' not in group_names"
    - "'shdeployer' not in group_names"
    - "'clustermanager' not in group_names"

- name: Configure client name in deploymentclient.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: 'deployment-client'
    option: clientName
    value: "{{ clientName }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - clientName != 'undefined'
    - "'indexer' not in group_names"
    - "'search' not in group_names"
    - "'splunk_mgmt' not in group_names"
    - "'shdeployer' not in group_names"
    - "'clustermanager' not in group_names"

- name: Configure phoneHomeIntervalInSecs in deploymentclient.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: deployment-client
    option: phoneHomeIntervalInSecs
    value: "{{ phoneHomeIntervalInSecs }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - phoneHomeIntervalInSecs != 'undefined'
    - "'indexer' not in group_names"
    - "'search' not in group_names"
    - "'splunk_mgmt' not in group_names"
    - "'shdeployer' not in group_names"
    - "'clustermanager' not in group_names"

- name: Configure deployment server pass4SymmKey in server.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: deployment
    option: pass4SymmKey
    value: "{{ splunk_ds_key }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - splunk_ds_key != 'undefined'
    - "'indexer' not in group_names"
    - "'search' not in group_names"
    - "'splunk_mgmt' not in group_names"
    - "'shdeployer' not in group_names"
    - "'clustermanager' not in group_names"
