---
# Example host_vars for a deployment server that is leveraging the configure_serverclass.yml task to manage serverclass.conf
serverclasses:
# First server class example, basic definition:
  - serverclass: all_forwarders
    whitelist:
      - '*'
    blacklist:
      - 'indexer'
    apps:
      - name: ansible_all_forwarder_outputs
        options:
          restartSplunkd: 1
  - serverclass: cluster_manager
    whitelist:
      - 'clustermanager'
    apps:
      - name: ansible_cluster_manager_base
        options:
          restartSplunkd: 1
  - serverclass: all_license_slaves
    whitelist:
      - '*'
    blacklist:
      - 'splunk_mgmt'
    apps:
      - name: ansible_full_license_server 
        options:
          restartSplunkd: 1
