# Example playbook to install splunk and configure a basic SHC
# Ensure that the following vars are configured: ansible_user, ansible_ssh_private_key_file, splunk_admin_password, splunk_user_seed: true
- hosts:
    - shdeployer
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: check_splunk.yml
  vars_files:
    - /opt/ansible-role-for-splunk/roles/splunk/files/splunk_secrets.yml

- hosts:
    - shdeployer
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_deployer.yml
  vars_files:
    - /opt/ansible-role-for-splunk/roles/splunk/files/splunk_secrets.yml

- hosts:
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_members.yml
  vars_files:
    - /opt/ansible-role-for-splunk/roles/splunk/files/splunk_secrets.yml

- hosts:
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_captain.yml
  vars_files:
    - /opt/ansible-role-for-splunk/roles/splunk/files/splunk_secrets.yml
